name: deploy website

on:
  push:
    branches:
      - master
  release:
    types: [published]

concurrency:
  
  group: ${{ format('ci-{0}', github.ref) }}
  cancel-in-progress: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
jobs:
- name: deploying website OVH production server 
      if: |
        github.event_name == 'release' && 
        github.event.release.prerelease != true
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_OVH_HOST }}
        username: ${{ secrets.PROD_OVH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        passphrase: ${{ secrets.PROD_SSH_KEY_PASSPHRASE }}
        rm: true
        source: "docs/"
        target: "${{ secrets.PROD_OVH_DIR }}"
