
name: deploy website

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: deploying website OVH production server 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_OVH_HOST }}
          username: ${{ secrets.PROD_OVH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_KEY_PASSPHRASE }}
          rm: true
          source: "root"
          target: "${{ secrets.PROD_OVH_DIR }}"
